# Generated by Django 6.0.3 on 2026-03-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
